### PR TITLE
replacement of variables also for imported files + refactoring (split into multiple modules)

### PR DESCRIPTION
**Pull request by jens1205**
This PR adresses #56 (and thus also #55)

It changes the following:
- Do not give curl filenames anymore. Instead read the files and apply variable substitution to all lines
- Fix filename resolution for relative filenames for importfiles
- refactor codebase, splitting the code into multiple modules
- simplify handling of last() function and LastOpts

### CODE REVIEW

**Comment by jens1205** [comment]
Hi @NTBBloodbath ,

while implementing #56 I have also done some refactoring. I'd suggest to apply the four-eyes principle - do you mind to review the changes?

Regards

Jens

**Review by NTBBloodbath — APPROVED** [review]
Hey man, sorry for the delay, I was working haha

Thank you so much for this, being honest I haven't used the external bodies yet so I would never caught this bug by myself, nice catch!

I was also thinking since a long time to refact a ton of stuff here. I had a different idea about how things should be organized but this way also looks pretty good IMO.

Regarding to the four-eyes principle I didn't knew about it tbh so did a quick search on the web and the concept that I saw looks very good, I think that we should definitely use it, in that way we can improve a ton of stuff, including the transparency and that's a really good point. Let me know how can we start implementing this :)

Regards

**Comment by jens1205** [comment]
If this would be a Greenfield project my structure would also look a bit different. But this first refactoring was a trade off between better readability / maintainability ob one side and effort/risk on the other.

We could improve based on this. But for a comparable small project like this there is no strong need to have the best possible solution. 

Thanks for the review!

**Comment by NTBBloodbath** [comment]
Yeah, agreed. The code structure was pretty much of junk before, hopefully this refactoring will open the doors for future contributors and obviously for us too.

And no problem man, thank you for doing this!

**Pull request merged**
